#ifndef SIGNALTYPE_H
#define SIGNALTYPE_H

enum SignalType{
    PRINT,
    INDICATOR_LIGHT,
    SET_STATUS,
    POWER_INDICATOR,
    LIGHTUP_SHOCK,
    LIGHTUP_911,
    LIGHTUP_OK,
    LIGHTUP_COMPRESSIONS,
    LIGHTUP_PADS,
    LIGHTUP_STANDCLEAR
};


#endif // SIGNALTYPE_H
